title: Truebird Hack Lab
description: Hacking and Security Study Blog
url: https://truebird0109.github.io
baseurl: ""

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
